export { default as Home } from "./home/Home"
export { default as Shop } from "./shop/Shop"
export { default as SingleProduct } from "./single_product/SingleProduct"
export { default as Cart } from "./cart/Cart"
export { default as Checkout} from "./checkout/Checkout"
export { default as Contact} from "./contact/Contact"
export { default as ErrorPage} from "./error/ErrorPage"